export const managerHistoryListMock = {
  url: "https://linkedoutapp.com/api/admin-office/histories?page=1&limit=10&filter=all",
  apiResponse: {
    status: 200,
    contentType: "application/json",
    body: JSON.stringify({
      data: {
        histories: [
          {
            id: 16,
            actionType: "updated",
            target: "notice",
            comment: null,
            processor: {
              id: 2,
              email: "jah512@naver.com",
              name: "정아현",
              profileImage:
                "https://cdn.linkedoutapp.com/profile/c954dc1b-829f-4e4d-ae24-41e72ee4c185",
              activated: true,
              info: null,
            },
            processedDate: "2024-11-29T03:45:52.106+09:00",
            report: null,
            review: null,
            user: null,
            essay: null,
            notice: null,
            inquiry: null,
          },
          {
            id: 15,
            actionType: "updated",
            target: "notice",
            comment: null,
            processor: {
              id: 2,
              email: "jah512@naver.com",
              name: "정아현",
              profileImage:
                "https://cdn.linkedoutapp.com/profile/c954dc1b-829f-4e4d-ae24-41e72ee4c185",
              activated: true,
              info: null,
            },
            processedDate: "2024-11-29T03:41:23.978+09:00",
            report: null,
            review: null,
            user: null,
            essay: null,
            notice: null,
            inquiry: null,
          },
          {
            id: 14,
            actionType: "updated",
            target: "notice",
            comment: null,
            processor: {
              id: 2,
              email: "jah512@naver.com",
              name: "정아현",
              profileImage:
                "https://cdn.linkedoutapp.com/profile/c954dc1b-829f-4e4d-ae24-41e72ee4c185",
              activated: true,
              info: null,
            },
            processedDate: "2024-11-29T03:39:57.434+09:00",
            report: null,
            review: null,
            user: null,
            essay: null,
            notice: null,
            inquiry: null,
          },
          {
            id: 13,
            actionType: "updated",
            target: "notice",
            comment: null,
            processor: {
              id: 2,
              email: "jah512@naver.com",
              name: "정아현",
              profileImage:
                "https://cdn.linkedoutapp.com/profile/c954dc1b-829f-4e4d-ae24-41e72ee4c185",
              activated: true,
              info: null,
            },
            processedDate: "2024-11-29T03:39:54.741+09:00",
            report: null,
            review: null,
            user: null,
            essay: null,
            notice: null,
            inquiry: null,
          },
          {
            id: 12,
            actionType: "updated",
            target: "notice",
            comment: null,
            processor: {
              id: 2,
              email: "jah512@naver.com",
              name: "정아현",
              profileImage:
                "https://cdn.linkedoutapp.com/profile/c954dc1b-829f-4e4d-ae24-41e72ee4c185",
              activated: true,
              info: null,
            },
            processedDate: "2024-11-29T03:39:11.924+09:00",
            report: null,
            review: null,
            user: null,
            essay: null,
            notice: null,
            inquiry: null,
          },
          {
            id: 11,
            actionType: "updated",
            target: "notice",
            comment: null,
            processor: {
              id: 2,
              email: "jah512@naver.com",
              name: "정아현",
              profileImage:
                "https://cdn.linkedoutapp.com/profile/c954dc1b-829f-4e4d-ae24-41e72ee4c185",
              activated: true,
              info: null,
            },
            processedDate: "2024-11-29T03:39:06.232+09:00",
            report: null,
            review: null,
            user: null,
            essay: null,
            notice: null,
            inquiry: null,
          },
          {
            id: 10,
            actionType: "updated",
            target: "notice",
            comment: null,
            processor: {
              id: 2,
              email: "jah512@naver.com",
              name: "정아현",
              profileImage:
                "https://cdn.linkedoutapp.com/profile/c954dc1b-829f-4e4d-ae24-41e72ee4c185",
              activated: true,
              info: null,
            },
            processedDate: "2024-11-29T03:37:53.504+09:00",
            report: null,
            review: null,
            user: null,
            essay: null,
            notice: null,
            inquiry: null,
          },
          {
            id: 9,
            actionType: "updated",
            target: "notice",
            comment: null,
            processor: {
              id: 2,
              email: "jah512@naver.com",
              name: "정아현",
              profileImage:
                "https://cdn.linkedoutapp.com/profile/c954dc1b-829f-4e4d-ae24-41e72ee4c185",
              activated: true,
              info: null,
            },
            processedDate: "2024-11-29T03:33:52.825+09:00",
            report: null,
            review: null,
            user: null,
            essay: null,
            notice: null,
            inquiry: null,
          },
          {
            id: 8,
            actionType: "updated",
            target: "notice",
            comment: null,
            processor: {
              id: 2,
              email: "jah512@naver.com",
              name: "정아현",
              profileImage:
                "https://cdn.linkedoutapp.com/profile/c954dc1b-829f-4e4d-ae24-41e72ee4c185",
              activated: true,
              info: null,
            },
            processedDate: "2024-11-29T03:32:14.746+09:00",
            report: null,
            review: null,
            user: null,
            essay: null,
            notice: null,
            inquiry: null,
          },
          {
            id: 7,
            actionType: "updated",
            target: "notice",
            comment: null,
            processor: {
              id: 2,
              email: "jah512@naver.com",
              name: "정아현",
              profileImage:
                "https://cdn.linkedoutapp.com/profile/c954dc1b-829f-4e4d-ae24-41e72ee4c185",
              activated: true,
              info: null,
            },
            processedDate: "2024-11-29T03:08:23.654+09:00",
            report: null,
            review: null,
            user: null,
            essay: null,
            notice: null,
            inquiry: null,
          },
        ],
        totalPage: 2,
        page: 1,
        total: 16,
      },
    }),
  },
};

export const managerListMock = {
  url: "https://linkedoutapp.com/api/admin-info?page=1&limit=10&filter=all",
  apiResponse: {
    status: 200,
    contentType: "application/json",
    body: JSON.stringify({
      data: {
        admins: [
          {
            id: 5,
            email: "kkhyungyung0@naver.com",
            name: "김근형",
            profileImage: null,
            activated: true,
            info: null,
          },
          {
            id: 4,
            email: "guest@guest.com",
            name: "guest",
            profileImage: null,
            activated: true,
            info: null,
          },
          {
            id: 3,
            email: "dudgk0216@gmail.com",
            name: "슈짱",
            profileImage: null,
            activated: true,
            info: null,
          },
          {
            id: 2,
            email: "jah512@naver.com",
            name: "정아현",
            profileImage:
              "https://cdn.linkedoutapp.com/profile/c954dc1b-829f-4e4d-ae24-41e72ee4c185",
            activated: true,
            info: null,
          },
          {
            id: 1,
            email: "daechan476@gmail.com",
            name: "root",
            profileImage: null,
            activated: true,
            info: null,
          },
        ],
        total: 5,
        page: 1,
        totalPage: 1,
      },
    }),
  },
};
