export const reportListMock = {
  url: "https://linkedoutapp.com/api/admin-task/reports?sort=most&page=1&limit=10",
  apiResponse: {
    status: 200,
    contentType: "application/json",
    body: JSON.stringify({
      data: {
        totalReports: 6,
        totalEssay: 6,
        totalPage: 1,
        page: 1,
        reports: [
          {
            id: 1,
            title: "Unauthorized Access",
            content: "This content violates terms.",
            linkedOutGauge: 20,
            createdDate: "2024-12-09T16:21:20.569Z",
            updatedDate: "2024-12-10T10:05:30.000Z",
            thumbnail: "image1.png",
            bookmarks: true,
            views: 150,
            status: "Pending",
            deviceOS: "iOS",
            deviceType: "Smartphone",
            deviceModel: "iPhone 14",
            authorId: 101,
            reports: [
              {
                id: 1,
                reason: "Hate speech",
                processed: false,
                processedDate: null,
                createdDate: "2024-12-09T16:30:20.000Z",
                reporterId: 301,
              },
            ],
          },
          {
            id: 2,
            title: "Spam Content",
            content: "Buy this now!",
            linkedOutGauge: 50,
            createdDate: "2024-12-08T14:15:00.000Z",
            updatedDate: "2024-12-09T08:10:45.000Z",
            thumbnail: "image2.png",
            bookmarks: false,
            views: 80,
            status: "Reviewed",
            deviceOS: "Android",
            deviceType: "Tablet",
            deviceModel: "Galaxy Tab S7",
            authorId: 102,
            reports: [
              {
                id: 2,
                reason: "Spam",
                processed: true,
                processedDate: "2024-12-09T10:30:00.000Z",
                createdDate: "2024-12-08T14:30:00.000Z",
                reporterId: 302,
              },
            ],
          },
          {
            id: 3,
            title: "Offensive Language",
            content: "This post contains offensive words.",
            linkedOutGauge: 10,
            createdDate: "2024-12-07T18:00:00.000Z",
            updatedDate: "2024-12-08T09:00:00.000Z",
            thumbnail: "image3.png",
            bookmarks: true,
            views: 95,
            status: "Pending",
            deviceOS: "Windows",
            deviceType: "Desktop",
            deviceModel: "HP Pavilion",
            authorId: 103,
            reports: [
              {
                id: 3,
                reason: "Offensive Language",
                processed: false,
                processedDate: null,
                createdDate: "2024-12-07T18:15:00.000Z",
                reporterId: 303,
              },
            ],
          },
          {
            id: 4,
            title: "Misinformation",
            content: "False information about current events.",
            linkedOutGauge: 5,
            createdDate: "2024-12-06T12:00:00.000Z",
            updatedDate: "2024-12-07T15:00:00.000Z",
            thumbnail: "image4.png",
            bookmarks: false,
            views: 120,
            status: "Reviewed",
            deviceOS: "MacOS",
            deviceType: "Laptop",
            deviceModel: "MacBook Pro",
            authorId: 104,
            reports: [
              {
                id: 4,
                reason: "Misinformation",
                processed: true,
                processedDate: "2024-12-07T16:00:00.000Z",
                createdDate: "2024-12-06T12:15:00.000Z",
                reporterId: 304,
              },
            ],
          },
          {
            id: 5,
            title: "Copyright Infringement",
            content: "Unauthorized use of copyrighted material.",
            linkedOutGauge: 15,
            createdDate: "2024-12-05T10:00:00.000Z",
            updatedDate: "2024-12-06T11:00:00.000Z",
            thumbnail: "image5.png",
            bookmarks: true,
            views: 65,
            status: "Pending",
            deviceOS: "Linux",
            deviceType: "Server",
            deviceModel: "Dell PowerEdge",
            authorId: 105,
            reports: [
              {
                id: 5,
                reason: "Copyright Violation",
                processed: false,
                processedDate: null,
                createdDate: "2024-12-05T10:15:00.000Z",
                reporterId: 305,
              },
            ],
          },
          {
            id: 47,
            title: "Harassment",
            content: "Targeted harassment of an individual.",
            linkedOutGauge: 30,
            createdDate: "2024-12-04T16:00:00.000Z",
            updatedDate: "2024-12-05T17:00:00.000Z",
            thumbnail: "image6.png",
            bookmarks: false,
            views: 200,
            status: "Reviewed",
            deviceOS: "Android",
            deviceType: "Smartphone",
            deviceModel: "Pixel 7",
            authorId: 106,
            reports: [
              {
                id: 6,
                reason: "Harassment",
                processed: true,
                processedDate: "2024-12-05T18:00:00.000Z",
                createdDate: "2024-12-04T16:15:00.000Z",
                reporterId: 306,
              },
            ],
          },
          {
            id: 7,
            title: "Malicious Link",
            content: "This post contains harmful links.",
            linkedOutGauge: 45,
            createdDate: "2024-12-03T08:00:00.000Z",
            updatedDate: "2024-12-04T09:00:00.000Z",
            thumbnail: "image7.png",
            bookmarks: true,
            views: 175,
            status: "Pending",
            deviceOS: "Windows",
            deviceType: "Desktop",
            deviceModel: "Lenovo ThinkPad",
            authorId: 107,
            reports: [
              {
                id: 7,
                reason: "Malicious Content",
                processed: false,
                processedDate: null,
                createdDate: "2024-12-03T08:15:00.000Z",
                reporterId: 307,
              },
            ],
          },
          {
            id: 8,
            title: "Fake Account",
            content: "Suspected fake account activity.",
            linkedOutGauge: 0,
            createdDate: "2024-12-02T20:00:00.000Z",
            updatedDate: "2024-12-03T21:00:00.000Z",
            thumbnail: "image8.png",
            bookmarks: false,
            views: 50,
            status: "Reviewed",
            deviceOS: "iOS",
            deviceType: "Smartphone",
            deviceModel: "iPhone SE",
            authorId: 108,
            reports: [
              {
                id: 8,
                reason: "Impersonation",
                processed: true,
                processedDate: "2024-12-03T22:00:00.000Z",
                createdDate: "2024-12-02T20:15:00.000Z",
                reporterId: 308,
              },
            ],
          },
        ],
      },
    }),
  },
};
